const libreria = 
[
    {
        id: 1,
        nombre: "Cartuchera",
        tipo: "cartuchera",
        descripcion: "Cartuchera práctica y estilizada, ideal para organizar tus útiles escolares.",
        precio: "8000",
        img: ".png",
        cantidad: 0,
    },
    {
        id: 2,
        nombre: "Carpeta",
        tipo: "carpeta",
        descripción: "Carpeta resistente y elegante, perfecta para organizar documentos importantes.",
        precio: "4500",
        cantidad: 0,
    },
    {
        id: 3,
        nombre: "Mochila",
        tipo: "mochila",
        descripción: "Mochila duradera y cómoda, perfecta para transportar tus pertenencias diarias.",
        precio: "79999",
        cantidad: 0,
    },
    {
        id: 4,
        nombre: "Mochila Grande",
        tipo: "mochila",
        descripción: "Mochila grande y espaciosa, ideal para viajes y aventuras prolongadas.",
        precio: "120000",
        cantidad: 0,
    },
    {
        id: 5,
        nombre: "Cuaderno",
        tipo: "cuaderno",
        descripción: "Cuaderno de calidad, perfecto para tomar notas y organizar ideas.",
        precio: "3250",
        cantidad: 0,
    },
    {
        id: 6,
        nombre: "Cuaderno",
        tipo: "cuaderno",
        descripción: "Cuaderno de calidad, perfecto para tomar notas y organizar ideas.",
        precio: "3250",
        cantidad: 0,
    },
]